In [31]:
# numpy 사용하기
import numpy as np
x = np.array([3,1,2])
print(x)
print(type(x))
print(type([3,1,2]))

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
c = [[1],[1,2]]
d = np.array([[1,1],[1,2]])

for x,y in d:
    print(x,y)

In [21]:
x = np.array([1.0, 2.0, 3.0])  #"1.0", "2.0", "3.0" 이렇게 문자로 하면 오류뜸
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [22]:
print(x.shape)
print(x.dtype)  #dtype : data type
print(d.shape)
print(y/2.0) 

(3,)
float64
(2, 2)
[1. 2. 3.]


In [30]:
# numpy 관련 메소드 - ndim, shape
## 예제1
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)  #ndim : 차원수(괄호 갯수로 판단)
print(a.shape)  #shape : 차원의 크기를 튜플 형태로 표현(괄호 덩어리안에 덩어리들의 숫자로 표현)

2
(3, 2)


In [27]:
## 예제2
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)
print(a.shape)

3
(3, 2, 1)


In [29]:
## 예제3
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)
print(a.shape)

3
(3, 2, 2)


In [72]:
## 예제4
a = np.array([1,2,3])  #1차원이므로 하나씩 따로 봐서 shape이 3으로 출력
print(a.shape)

(3,)


In [32]:
# numpy 관련 메소드 - dot
np.dot(4,2)

8

In [33]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

24

In [34]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [37]:
# numpy 관련 메소드 - matmul
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [43]:
# numpy 관련 메소드 - flatten
ndar3 = np.array([[[1],[2]],[[3],[4]]])
print(ndar3.shape)
print(ndar3.ndim)
a = ndar3.flatten()
print(a)
print(a.shape)
print(a.ndim)

(2, 2, 1)
3
[1 2 3 4]
(4,)
1


In [48]:
# numpy 관련 메소드 - reshape
ndar4 = np.array([[1,2],[2,3],[3,4]])  #3x2=6 -> reshape할 때 개수가 같아야함
ndar4.reshape(2,3)  #2x3=6
ndar4.reshape(1,6)  #1x6=6
##ndar4.reshape(2,4)  #2x4=8이므로 얘는 안됨

array([[1, 2, 2, 3, 3, 4]])

In [53]:
# numpy 관련 메소드 - random
np.random.randint(5, size=(2,4))
np.random.rand(2,4)

array([[0.282676  , 0.81909712, 0.97792216, 0.65949916],
       [0.99147547, 0.37060438, 0.15155784, 0.74929525]])

In [60]:
# numpy 관련 메소드 - random - RNG(최신 동향)
rng = np.random.default_rng()
rng.random()

0.12141874547895182

In [ ]:
rng.integers(0,10,(2,4))

array([[1, 5, 3, 8],
       [2, 1, 6, 7]], dtype=int64)

In [61]:
# numpy 관련 메소드 - 조건식
ndar5 = np.array([[6,3],[5,2],[4,1]])
ndar5 > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [62]:
ndar5[ndar5 > 4]

array([6, 5])

In [65]:
ndar5[[[True, False],
       [True, False],
       [False, False]]]

array([6, 5])

In [66]:
ndar5[ndar5 > 7]

array([], dtype=int32)

In [68]:
ndar5[ndar5 > 1]

array([6, 3, 5, 2, 4])

In [71]:
ndar5[1:]  #리스트 슬라이싱도 가능

array([[5, 2],
       [4, 1]])