In [33]:
# 실습1. Numpy 모듈 사용해보기1
##1
import numpy as np
ndar1 = np.zeros(10)
print(ndar1)

##2
ndar2 = ndar1
ndar2[4] = 1
print(ndar2)

##3
ndar3 = np.arange(10,31)
print(ndar3)

##4
ndar4 = np.random.randint(100, size=(2,2))
print(ndar4)
###최신방법
rng = np.random.default_rng(1)
ndar4_1 = rng.integers(100, size = (2,2))
print(ndar4_1)

##5
ndar5 = np.random.rand(2,4)
print(ndar5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[32  9]
 [88 87]]
[[47 51]
 [75 95]]
[[0.86615197 0.50372041 0.79551062 0.47084824]
 [0.71893771 0.35228386 0.44047413 0.21123305]]


In [108]:
##6
ndar6 = np.arange(35,75)
print(ndar6)
ndar6_1 = ndar6.reshape(10,4)
print(ndar6_1)
###방법2 - 그냥 shape 사용해도됨
# ndar6.shape = (10,4)
# print(ndar6)

##7
ndar7 = ndar6_1[::-1]
print(ndar7)

##8
ndar8 = ndar6_1[1:-1,2:]
print(ndar8)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [116]:
##9
ndar9 = ndar6_1[:,-1]
print(ndar9)
print(ndar9.ndim)

##9-1
ndar9_1 = ndar9.reshape(10,1)
print(ndar9_1)
print(ndar9_1.ndim)
###방법2 - 6번을 이용해서(이게 완벽한 정답)
# ndar9_1 = ndar6_1[:, -1:]
# print(ndar9_1)
# print(ndar9_1.ndim)

##10
ndar10 = ndar9_1[::-1]
print(ndar10)

##11
ndar11 = np.random.randint(1,51, size=(5,6))
print(ndar11)
ndar11_1 = (ndar11 % 2 == 0)
print(ndar11[ndar11_1])

[38 42 46 50 54 58 62 66 70 74]
1
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
2
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[ 4 42  7 18 28 40]
 [39  9 47 46 12 22]
 [26 40 32  1 39 37]
 [45 20 11 17 31  3]
 [ 2 11 17 45 32 35]]
[ 4 42 18 28 40 46 12 22 26 40 32 20  2 32]


In [140]:
# 차원 확장
import numpy as np
a = np.array([[1,2],[3,4]])
expanded = np.expand_dims(a,0)
print(a.shape)
print(expanded)
print(expanded.shape)

expanded = np.expand_dims(a,1)
print(expanded)
print(expanded.shape)

expanded = np.expand_dims(a,2)
print(expanded)
print(expanded.shape)

(2, 2)
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [163]:
# 차원 축소
import numpy as np
np_ones = np.ones((1,2,1,3))
print(np_ones)

squeezed = np.squeeze(np_ones)
print(squeezed)
print(squeezed.shape)

squeezed = np.squeeze(np_ones, 0)
print(squeezed)
print(squeezed.shape)

squeezed = np.squeeze(np_ones, 2)
print(squeezed)
print(squeezed.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)


In [167]:
# 중복 제거
import numpy as np
a = [1,2,2,3,4,3,4,3,1]
u_a, counts = np.unique(a, return_counts=True)
print(u_a)
print(counts)

a = [1,2,2,3,4,3,4,3,1]
u_a, indexs = np.unique(a, return_index=True)
print(u_a)
print(indexs)

a = [1,2,2,3,4,3,4,3,1]
u_a, indexs, counts = np.unique(a, return_index=True, return_counts=True)
print(u_a)
print(indexs)
print(counts)

[1 2 3 4]
[2 2 3 2]
[1 2 3 4]
[0 1 3 4]
[1 2 3 4]
[0 1 3 4]
[2 2 3 2]


In [168]:
# 정렬
import numpy as np
a = np.array([1,4,2,3])
b = np.sort(a)  #a[np.argsort(a)]와 동일
c = np.argsort(a)
print(f"a {a}")
print(f"b {b}")
print(f"c {c}")
print(f"cc {a[c]}")
a.sort()
print(f"a {a}")
# a[c.sort()]  #바로 위에 두 줄 지우고 이거하면 다시 a값으로 돌아감 -> 왜??

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]


In [155]:
# 그 밖에 유용한 함수
import numpy as np
a = np.array([1,4,2,3])
np.mean(a)
np.std(a)
np.var(a)
np.max(a)
np.min(a)
np.sum(a)
np.prod(a)
np.median(a)


2.5

In [175]:
# 그 밖에 유용한 함수 - 2차원에서 예제(axis넣어서 열과 행으로 나눠서 계산 가능)
import numpy as np
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

a = np.sort(x, axis=0)  #axis=0 -> 행 기준 ||
print(a)

b= np.sort(x,axis=1)  #axis=1 -> 열 기준 =
print(b)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]
[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [183]:
# 실습2. Numpy 모듈 사용해보기2
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
##1
import numpy as np
u_a = np.unique(a)
print(u_a)

##2
print(f"최대 : {np.max(u_a)}")
print(f"최소 : {np.min(u_a)}")
print(f"평균값 : {np.mean(u_a)}")

##3
print(f"합 : {np.sum(u_a)}")

##4
print(f"중복제거x배열 중간값 : {np.median(a)}")

[  1   2   3   4   5   7   8   9  10  11  24 100]
최대 : 100
최소 : 1
평균값 : 15.333333333333334
합 : 184
중복제거x배열 중간값 : 5.0


In [249]:
# 실습3. Numpy 모듈 사용해보기3
import numpy as np
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
print(x)
##1
max_1 = np.max(x[:,0])
print(f"1열 최대값 : {max_1}")
min_1 = np.min(x[:,0])
print(f"1열 최소값 : {min_1}")
mean_1 = np.mean(x[:,0])
print(f"1열 평균값 : {mean_1}")

##2
sum_2 = np.sum(x[1])
print(f"2행 모든 합: {sum_2}")

##3
a = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
b = np.argsort(a)
c = b[::-1]
print(a[c])

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
1열 최대값 : 0
1열 최소값 : -99
1열 평균값 : -66.0
2행 모든 합: -283
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
